#!/bin/bash
# Compares a file in current quilt tree with the commit id in patch's
# description
. libparsemail.sh

CONFIG=$HOME/.config/qtools/config.sh
if [ ! -f $CONFIG ]; then
	echo "Unable to find the configuration file. Please create one at $CONFIG with UPSTREAM=<path to Linus' tree>" >&2;
	exit 1;
fi
. $CONFIG;

if [ -z "$1" ]; then
	echo "$0 <file>" >&2;
	exit 1;
fi
file=$1;

commit=$(get_git_references patches/$(quilt top) | head -n 1);
if [ -z "$commit" ]; then
	echo "couldn't find a commit id on the patch's description" >&2;
	exit 1;
fi

tmp=$(mktemp);
pushd $UPSTREAM;
git show $commit:$1 >$tmp;
popd

vimdiff $file $tmp;
#vimdiff -R -c ":diffoff" patches/$(quilt top) $file $tmp

rm -f $tmp;
