#!/bin/bash
. libparsemail.sh

CONFIG=$HOME/.config/qtools/config.sh
if [ ! -f $CONFIG ]; then
	echo "Unable to find the configuration file. Please create one at $CONFIG with UPSTREAM=<path to Linus' tree>" >&2;
	exit 1;
fi
. $CONFIG;

tmp=$(mktemp);

for commit in $(get_git_commit patches/$(quilt top)); do
	pushd $UPSTREAM;
	git log -1 -p $commit >$tmp;
	popd
	vimdiff patches/$(quilt top) $tmp;
done
rm -f $tmp;
