#!/bin/bash
. libparsemail.sh

CONFIG=$HOME/.config/qtools/config.sh
if [ ! -f $CONFIG ]; then
	echo "Unable to find the configuration file. Please create one at $CONFIG with UPSTREAM=<path to Linus' tree>" >&2;
	exit 1;
fi
. $CONFIG;

tmp=$(mktemp);

commit=$(get_git_commit patches/$(quilt top));
pushd $UPSTREAM >/dev/null;
git log -1 -p $commit >$tmp;
popd >/dev/null;
umatch.py patches/$(quilt top) $tmp;
rc=$?;
rm -f $tmp;
if [ $rc = 0 ]; then
	echo "true";
else
	echo "false";
fi
exit $?;
