#!/bin/bash
. libparsemail.sh

tmp=$(mktemp);

function cleanup
{
	rm -f $tmp;
}
trap cleanup EXIT

function get_ystream_commit
{
	quilt header | grep Y-Commit | sed -e "s/.*Y-Commit:\ \([a-f0-9]*\).*/\1/";
}

commit=$(get_ystream_commit);
if [ -z "$commit" ]; then
	echo "Couldn't find 'Y-Commit' in the header. Are you sure this is a zstream patch?" >&2;
	exit 1;
fi
git log -1 -p $commit >$tmp;
vimdiff patches/$(quilt top) $tmp;

